version: '2.3'
services:
  employees_rest_api:
    container_name: restapi
    image: ${DOCKER_IMAGE_NAME:-employees-api}:${DOCKER_IMAGE_TAG:-latest}
    restart: unless-stopped
    build:
      dockerfile: employees_api/Dockerfile
      context: .
    environment:
    - FLASK_APP=server.py
    - HOST=${SERVICE_HOST:-0.0.0.0}
    - PORT=${SERVICE_PORT:-8080}
    - DB_FILE=chinook.db
    - FLASK_ENV=${ENVIRONMENT:-development}
    - API_PREFIX=/api
    volumes:
    - ./data:/app/data
    entrypoint:
    - python
    command:
    - /app/server.py

  frontend_nginx:
    container_name: frontend-nginx
    build:
      context: frontend
    image: frontend_nginx:${DOCKER_IMAGE_TAG:-latest}
    command: 
    - nginx
    - -g
    - daemon off;
    #command: tail -f /dev/null # for debugging
    environment:
    - API_SERVER=restapi:8080
    ports:
    - 8080:8080